#!/usr/bin/env ruby
print "Content-Type: text/html\n\n"
print "<html>\n"
print "<head>\n"
print "<title>CGI Test</title>\n"
print "</head>\n"
print "<body>\n"
print "Hello CGI!\n"
print "</body>\n"
print "</html>\n"
